CREATE TABLE `USER_ACCOUNT` (
	`useraccnum`	CHAR(4)	NOT NULL,
	`title`	VARCHAR(30)	NULL,
	`entid`	VARCHAR(30)	NULL,
	`entdate`	DATE	NULL,
	`entprogram`	VARCHAR(100)	NULL,
	`modid`	VARCHAR(30)	NULL,
	`moddate`	DATE	NULL,
	`modprogram`	VARCHAR(100)	NULL,
	`comp_idx`	INT	NOT NULL
);

CREATE TABLE `ACCOUNT_ABS` (
	`idx`	INT	NOT NULL,
	`memo`	VARCHAR(1000)	NULL,
	`entid`	VARCHAR(30)	NULL,
	`entdate`	DATE	NULL,
	`entprogram`	VARCHAR(100)	NULL,
	`modid`	VARCHAR(30)	NULL,
	`moddate`	DATE	NULL,
	`modprogram`	VARCHAR(100)	NULL,
	`comp_idx`	INT	NOT NULL,
	`user_useraccnum`	CHAR(4)	NOT NULL
);

CREATE TABLE `CUSTOMER` (
	`usercustcode`	CHAR(5)	NOT NULL,
	`regcode`	CHAR(10)	NULL,
	`compname`	VARCHAR(255)	NULL,
	`CEO`	CHAR(8)	NULL,
	`phone`	VARCHAR(20)	NULL,
	`fax`	VARCHAR(20)	NULL,
	`email`	VARCHAR(255)	NULL,
	`bankname`	VARCHAR(30)	NULL,
	`workname`	CHAR(8)	NULL,
	`workphone`	VARCHAR(20)	NULL,
	`meno`	VARCHAR(1000)	NULL,
	`entid`	VARCHAR(30)	NULL,
	`entdate`	DATE	NULL,
	`entprogram`	VARCHAR(100)	NULL,
	`modid`	VARCHAR(30)	NULL,
	`moddate`	DATE	NULL,
	`modprogram`	VARCHAR(100)	NULL,
	`comp_idx`	INT	NOT NULL
);

CREATE TABLE `STATEMENT` (
	`num`	VARCHAR(255)	NOT NULL,
	`date`	DATE	NULL,
	`classify`	VARCHAR(30)	NULL,
	`debncre`	INT	NULL,
	`entid`	VARCHAR(30)	NULL,
	`entdate`	DATE	NULL,
	`entprogram`	VARCHAR(100)	NULL,
	`modid`	VARCHAR(30)	NULL,
	`moddate`	DATE	NULL,
	`modprogram`	VARCHAR(100)	NULL,
	`cus_usercustcode`	CHAR(5)	NOT NULL,
	`comp_idx`	INT	NOT NULL,
	`abs_idx`	INT	NOT NULL,
	`user_id`	VARCHAR(30)	NOT NULL,
	`accnum0`	CHAR(4)	NOT NULL
);

CREATE TABLE `USER` (
	`id`	VARCHAR(30)	NOT NULL,
	`name`	CHAR(8)	NULL,
	`password`	BINARY(32)	NULL,
	`email`	VARCHAR(255)	NULL,
	`phone`	VARCHAR(20)	NULL,
	`authority`	INT	NULL,
	`comp_idx`	INT	NOT NULL
);

CREATE TABLE `COMPANY` (
	`idx`	INT	NOT NULL,
	`compname`	VARCHAR(255)	NULL,
	`regcode`	CHAR(10)	NULL,
	`fax`	VARCHAR(20)	NULL,
	`phone`	VARCHAR(20)	NULL,
	`email`	VARCHAR(255)	NULL,
	`bankname`	VARCHAR(30)	NULL
);

CREATE TABLE `STD_ACCOUNT` (
	`stdaccnum`	CHAR(4)	NOT NULL,
	`title`	VARCHAR(30)	NULL
);

CREATE TABLE `ACCOUNT` (
	`accnum`	CHAR(4)	NOT NULL,
	`rel`	CHAR(4)	NULL,
	`entid`	VARCHAR(30)	NULL,
	`entdate`	DATE	NULL,
	`entprogram`	VARCHAR(100)	NULL,
	`modid`	VARCHAR(30)	NULL,
	`moddate`	DATE	NULL,
	`modprogram`	VARCHAR(100)	NULL,
	`idx`	INT	NOT NULL
);

ALTER TABLE `USER_ACCOUNT` ADD CONSTRAINT `PK_USER_ACCOUNT` PRIMARY KEY (
	`useraccnum`
);

ALTER TABLE `ACCOUNT_ABS` ADD CONSTRAINT `PK_ACCOUNT_ABS` PRIMARY KEY (
	`idx`
);

ALTER TABLE `CUSTOMER` ADD CONSTRAINT `PK_CUSTOMER` PRIMARY KEY (
	`usercustcode`
);

ALTER TABLE `STATEMENT` ADD CONSTRAINT `PK_STATEMENT` PRIMARY KEY (
	`num`
);

ALTER TABLE `USER` ADD CONSTRAINT `PK_USER` PRIMARY KEY (
	`id`
);

ALTER TABLE `COMPANY` ADD CONSTRAINT `PK_COMPANY` PRIMARY KEY (
	`idx`
);

ALTER TABLE `STD_ACCOUNT` ADD CONSTRAINT `PK_STD_ACCOUNT` PRIMARY KEY (
	`stdaccnum`
);

ALTER TABLE `ACCOUNT` ADD CONSTRAINT `PK_ACCOUNT` PRIMARY KEY (
	`accnum`
);

ALTER TABLE `USER_ACCOUNT` ADD CONSTRAINT `FK_COMPANY_TO_USER_ACCOUNT_1` FOREIGN KEY (
	`comp_idx`
)
REFERENCES `COMPANY` (
	`idx`
);

ALTER TABLE `ACCOUNT_ABS` ADD CONSTRAINT `FK_COMPANY_TO_ACCOUNT_ABS_1` FOREIGN KEY (
	`comp_idx`
)
REFERENCES `COMPANY` (
	`idx`
);

ALTER TABLE `ACCOUNT_ABS` ADD CONSTRAINT `FK_USER_ACCOUNT_TO_ACCOUNT_ABS_1` FOREIGN KEY (
	`user_useraccnum`
)
REFERENCES `USER_ACCOUNT` (
	`useraccnum`
);

ALTER TABLE `CUSTOMER` ADD CONSTRAINT `FK_COMPANY_TO_CUSTOMER_1` FOREIGN KEY (
	`comp_idx`
)
REFERENCES `COMPANY` (
	`idx`
);

ALTER TABLE `STATEMENT` ADD CONSTRAINT `FK_CUSTOMER_TO_STATEMENT_1` FOREIGN KEY (
	`cus_usercustcode`
)
REFERENCES `CUSTOMER` (
	`usercustcode`
);

ALTER TABLE `STATEMENT` ADD CONSTRAINT `FK_COMPANY_TO_STATEMENT_1` FOREIGN KEY (
	`comp_idx`
)
REFERENCES `COMPANY` (
	`idx`
);

ALTER TABLE `STATEMENT` ADD CONSTRAINT `FK_ACCOUNT_ABS_TO_STATEMENT_1` FOREIGN KEY (
	`abs_idx`
)
REFERENCES `ACCOUNT_ABS` (
	`idx`
);

ALTER TABLE `STATEMENT` ADD CONSTRAINT `FK_USER_TO_STATEMENT_1` FOREIGN KEY (
	`user_id`
)
REFERENCES `USER` (
	`id`
);

ALTER TABLE `STATEMENT` ADD CONSTRAINT `FK_ACCOUNT_TO_STATEMENT_1` FOREIGN KEY (
	`accnum0`
)
REFERENCES `ACCOUNT` (
	`accnum0`
);

ALTER TABLE `USER` ADD CONSTRAINT `FK_COMPANY_TO_USER_1` FOREIGN KEY (
	`comp_idx`
)
REFERENCES `COMPANY` (
	`idx`
);

ALTER TABLE `ACCOUNT` ADD CONSTRAINT `FK_USER_ACCOUNT_TO_ACCOUNT_1` FOREIGN KEY (
	`accnum`
)
REFERENCES `USER_ACCOUNT` (
	`useraccnum`
);

ALTER TABLE `ACCOUNT` ADD CONSTRAINT `FK_USER_ACCOUNT_TO_ACCOUNT_2` FOREIGN KEY (
	`rel`
)
REFERENCES `USER_ACCOUNT` (
	`useraccnum`
);

ALTER TABLE `ACCOUNT` ADD CONSTRAINT `FK_STD_ACCOUNT_TO_ACCOUNT_1` FOREIGN KEY (
	`accnum`
)
REFERENCES `STD_ACCOUNT` (
	`stdaccnum`
);

ALTER TABLE `ACCOUNT` ADD CONSTRAINT `FK_STD_ACCOUNT_TO_ACCOUNT_2` FOREIGN KEY (
	`rel`
)
REFERENCES `STD_ACCOUNT` (
	`stdaccnum`
);

ALTER TABLE `ACCOUNT` ADD CONSTRAINT `FK_COMPANY_TO_ACCOUNT_1` FOREIGN KEY (
	`idx`
)
REFERENCES `COMPANY` (
	`idx`
);

